algoritmo "ContagemTabuada"
var
   contador,numero:inteiro


inicio

//Laço While

   escreva ("Digite  um numero:")
   leia(numero)

// observar o que quero executar
   contador <-1
   enquanto (contador<11)faca
      escreval (numero," x",contador," =",numero*contador)
//bloco de codigos se a codição for verdadeira
//primeiro irá exibir depois contar
      contador<-contador+1
   fimenquanto







fimalgoritmo