algoritmo "ProcedimentoCorFavorita"

procedimento nomeCor()
inicio

   //bloco de códigos que será executado
   //assim que o procedimento for chamado
   limpatela
   escreval ("Pazer ", nome ,"  minha cor favorita é ", cor)
fimprocedimento

var

   nome,cor: caracter

inicio

   escreval ("Digite seu nome: ")
   leia(nome)
   escreval ("Qual sua cor favorita?")
   leia(cor)
   nomeCor()

fimalgoritmo